apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: book-store-app
  namespace: argocd
  annotations:
    # Watch THIS container image (must match your Deployment & Kustomize)
    argocd-image-updater.argoproj.io/image-list: book-store=docker.io/haythem22/book-store-gitops

    # Write back to Git
    argocd-image-updater.argoproj.io/write-back-method: git:secret:argocd/git-creds
    argocd-image-updater.argoproj.io/git-branch: main

    # Kustomize 'images:' writer
    argocd-image-updater.argoproj.io/write-back-target: kustomization

    # Use the new strategy name
    argocd-image-updater.argoproj.io/book-store.update-strategy: newest-build

    # Use the Docker Hub pull secret we just made
    argocd-image-updater.argoproj.io/pull-secret: pullsecret:argocd/dockerhub
spec:
  project: default
  source:
    repoURL: https://github.com/<you>/book-store-gitops
    targetRevision: main
    path: book-app
    kustomize: {}
  destination:
    server: https://kubernetes.default.svc
    namespace: book-store
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
